spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  datasource:
    username: my_new_user
    password: my_new_user
    url: jdbc:mysql://my-new.cs4i16kyfber.ap-northeast-2.rds.amazonaws.com:3306/my_new
    driver-class-name: com.mysql.cj.jdbc.Driver

github:
  clientId: 6d91f0584d549619c938
  clientSecret: 1be1156486024de0c78d6d039ec0ff7f111918ef
google:
  clientId: 737679013674-q9efp32jd44hu4gmetvavqr64d9rj97h.apps.googleusercontent.com
  clientSecret: XBnvqLH9rpK9P2aNkSouUhwY